## 1. Perform a set of exercises :


## Exercice03

In [2]:
#ex03
import numpy as np
n =int(input(" enter the number :"))
m =int(input(" enter the number :"))
r =int(input(" enter the number :"))
c=int(input(" enter the number :"))
arr = np.ones((n, m), dtype=int)

arr[::r, :] = 0
arr[:,::c] = 0
print(arr)


 enter the number :4
 enter the number :3
 enter the number :2
 enter the number :4
[[0 0 0]
 [0 1 1]
 [0 0 0]
 [0 1 1]]


## Execice04

In [1]:
#ex04
import numpy as np

n =int(input(" enter the number :"))
m =int(input(" enter the number :"))
arr = np.zeros((m, n), dtype=int)

arr[0,:] = np.arange(0, n)
print(arr)

 enter the number :3
 enter the number :4
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## Exercice5

In [9]:
import numpy as np
n =int(input(" enter"))
arr = np.zeros((n, n), dtype=int)
arr[::2, ::] = 1
print(arr)

 enter43
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]


## Exercice06

In [2]:
#ex06
import numpy as np

def matr(arr):
    arr[arr != 0] = -1
    return arr
a = np.array([int(i) for i in input(": ").split()])
print(matr(a))

: 4
[-1]


## Exercice10

In [5]:
#ex10
import numpy as np

def rndm(n,m):
    arr = np.random.random((n,m))
    print(arr.max())
    print(arr.min())
    print(arr.mean())
    print(arr.std())
rndm(4,4)


0.9636634291034424
0.14369484979224267
0.5487417642206559
0.2674110036541431


## Exercice12

In [6]:
#ex12
import numpy as np

n =int(input(" enter"))
arr = np.ones((n, n), dtype=int)
arr[0] = 0
arr[-1] = 0
arr[:, 0] = 0
arr[:, -1] = 0
print(arr)
arr[0]=0

 enter3
[[0 0 0]
 [0 1 0]
 [0 0 0]]


## Exercice17

In [8]:
#ex17
import numpy as np

n = int(input("Enter a number : "))
x = np.arange(n+1)
l, r = np.split(x, [n//4+1])
r[r < 3*n/4] = 0
print(x)

Enter a number : 5
[0 1 0 0 4 5]


## Exercice18

In [13]:
def ex18(n):
    arr = np.arange(0,n+1)
    arr[(arr < n/2) ^ (arr > 3*n/4)] *= -1
    return arr
print(ex18(18))

[  0  -1  -2  -3  -4  -5  -6  -7  -8   9  10  11  12  13 -14 -15 -16 -17
 -18]


## Exercice21

In [11]:
#ex21
import numpy as np

def rndm21(n):
    arr = np.random.random(n)
    arr1 = np.where(arr == arr.max(), 0, arr)
    return arr, arr1
for a in rndm21(17):
    print(a)

[0.56840418 0.05000406 0.83697551 0.48172893 0.50406502 0.85690344
 0.51750762 0.80371276 0.14726981 0.40324515 0.57372941 0.98254638
 0.88510847 0.48881952 0.37292945 0.97926107 0.23847287]
[0.56840418 0.05000406 0.83697551 0.48172893 0.50406502 0.85690344
 0.51750762 0.80371276 0.14726981 0.40324515 0.57372941 0.
 0.88510847 0.48881952 0.37292945 0.97926107 0.23847287]


## 2. Solve the system of linear equations using Cramer's formulas and perform a test using:

In [14]:
#solve_by_Cramer
def cramer(mA, B):
    n = mA.shape[0]
    det = np.linalg.det(mA)
    xs = np.empty(n)
    if det == 0:
        return None
    for i in range(n):
        mAi = np.copy(mA)
        mAi[:, i] = B
        xs[i] = np.linalg.det(mAi) / det
    return xs
A = np.array([[2, -1 ,3 ,2 ], [3,3,3 ,2 ], [3,-1 ,-1 ,2 ], [3,-1,3 ,-1 ]])
B = np.array([4, 6, 6, 6])
roots = cramer(A, B)
print(roots)
print(np.linalg.solve(A,B))
ax = np.dot(A,roots)
print(ax)
print(np.allclose(ax, B))

[ 2.00000000e+00 -4.54182146e-17  4.54182146e-17  6.05576195e-17]
[ 2.00000000e+00 -4.54182146e-17  4.54182146e-17  6.05576195e-17]
[4. 6. 6. 6.]
True


## 3. Calculate the value of the matrix expression:

In [17]:
#MATRIX
A = np.array([[3,2,-5],[4,2,0],[1 , 1,2]], dtype=int)
B = np.array([[-1,2,4],[0,3,2],[-1,-3,4]], dtype=int)

print((A-(B*B))*(2*A+B))

[[  10  -12  126]
 [  32  -49   -8]
 [   0    8 -112]]


## 4. Solve the matrix equation using an inverse matrix and perform a test using:

In [22]:
#inverse_Matrix2
a = np.array([[1,4,2],[2,1,-2],[0,1,1]])
b = np.array([[4,6,-2],[4,10,1],[2,4,-5]])
def solve(mA, mB):
    if np.linalg.det(mA) == 0:
        return None
    X = np.linalg.inv(mA) @ mB
    return X


roots = solve(a,b)
print(roots)
print(np.linalg.solve(a,b))
toor = a @ roots
print(toor)
print(np.allclose(toor,b))

[[ 16.  42. -42.]
 [ -8. -22.  25.]
 [ 10.  26. -30.]]
[[ 16.  42. -42.]
 [ -8. -22.  25.]
 [ 10.  26. -30.]]
[[ 4.  6. -2.]
 [ 4. 10.  1.]
 [ 2.  4. -5.]]
True
